server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka  # define a branch a ser utilizada
          uri: https://github.com/Daniel-Penelva/microservico-springboot3
          search-paths: config-data
  application:
    name: config-server

# A propriedade "search-paths" e o valor "config-data" � o nome da pasta onde vai ter os arquivos (.yaml) das configura��es dos servidores de cada microservi�o - est� pasta ficar� na pasta raiz do projeto.
